# Generated by Django 3.2.19 on 2023-06-25 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_buses', to='bus_system.station'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='start_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='starting_buses', to='bus_system.station'),
        ),
    ]
