# Generated by Django 3.2.19 on 2023-06-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_system', '0002_auto_20230625_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='chairs',
            field=models.ManyToManyField(blank=True, related_name='buses', to='bus_system.Chair'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='passing_stations',
            field=models.ManyToManyField(blank=True, related_name='passing_buses', to='bus_system.Station'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='passing_locations',
            field=models.ManyToManyField(related_name='passing_trips', to='bus_system.Station'),
        ),
    ]
