# Generated by Django 3.2.19 on 2023-06-25 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus_system', '0003_auto_20230625_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='destination_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Destination_trips', to='bus_system.station'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starting_trips', to='bus_system.station'),
        ),
    ]
