# Generated by Django 3.2.19 on 2023-06-25 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_system', '0004_auto_20230625_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='status',
        ),
    ]
