# Generated by Django 3.2.19 on 2023-06-25 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus_system', '0005_remove_trip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chair',
            name='price_per_chair',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='chair',
            name='chair_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bus_system.chairtype'),
        ),
        migrations.AlterField(
            model_name='chair',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('booked', 'Booked')], default='available', max_length=50),
        ),
    ]
