# Generated by Django 3.2.19 on 2023-06-25 16:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus_system', '0006_auto_20230625_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='destination_location',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='passing_locations',
        ),
        migrations.AddField(
            model_name='station',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5, validators=[django.core.validators.MinValueValidator(9)]),
        ),
        migrations.AddField(
            model_name='trip',
            name='end_location',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='ending_trips', to='bus_system.station'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='start_date',
            field=models.DateField(default='2023-06-25'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
        migrations.CreateModel(
            name='TripSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.TimeField()),
                ('travel_date', models.DateField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='bus_system.trip')),
            ],
            options={
                'unique_together': {('trip', 'travel_date', 'departure_time')},
            },
        ),
    ]
