# Generated by Django 3.2.19 on 2023-06-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_system', '0007_auto_20230625_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='distance',
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
