# Generated by Django 3.2.19 on 2023-06-25 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_system', '0008_auto_20230625_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5, validators=[django.core.validators.MinValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='bus',
            name='name',
            field=models.CharField(default='bus', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='price_per_chair',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='station',
            name='buses',
            field=models.ManyToManyField(blank=True, related_name='stations', to='bus_system.Bus'),
        ),
    ]
