# Generated by Django 3.2.19 on 2023-06-25 16:41

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_system', '0009_auto_20230625_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='duration',
            field=models.DurationField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.timedelta(0))]),
        ),
    ]
