# Generated by Django 3.2.19 on 2023-06-25 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus_system', '0010_trip_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.DateTimeField()),
                ('departure_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_system.station')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_system.trip')),
            ],
        ),
    ]
