# Generated by Django 3.2.19 on 2023-06-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_system', '0011_tripstop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tripstop',
            name='departure_time',
            field=models.TimeField(),
        ),
    ]
