# Generated by Django 3.2.19 on 2023-06-25 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus_system', '0013_auto_20230625_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='end_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ending_trips', to='bus_system.location'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starting_trips', to='bus_system.location'),
        ),
    ]
