# Generated by Django 3.2.19 on 2023-06-25 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_system', '0014_auto_20230625_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='day_of_week',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
