# Generated by Django 3.2.19 on 2023-06-25 19:14

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bus_system', '0015_auto_20230625_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='chairs',
        ),
        migrations.AlterField(
            model_name='trip',
            name='day_of_week',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], max_length=13),
        ),
    ]
