# Generated by Django 3.2.19 on 2023-06-29 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_system', '0017_auto_20230629_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='passing_stations',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='start_station',
        ),
    ]
