# Generated by Django 3.2.19 on 2023-06-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_system', '0018_auto_20230629_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chair',
            name='number',
            field=models.IntegerField(),
        ),
    ]
