# Generated by Django 3.2.19 on 2023-06-29 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus_system', '0021_alter_chair_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chair',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bus_chairs', to='bus_system.bus'),
        ),
    ]
