# Generated by Django 3.2.19 on 2023-06-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_system', '0023_remove_bus_chairs'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='chairs',
            field=models.ManyToManyField(blank=True, related_name='buses', to='bus_system.Chair'),
        ),
    ]
