# Generated by Django 3.2.19 on 2023-06-29 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_system', '0024_bus_chairs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='chairs',
        ),
    ]
