# Generated by Django 3.2.19 on 2023-07-04 23:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bus_system', '0025_remove_bus_chairs'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='bus', max_length=100)),
                ('number_of_chairs', models.PositiveIntegerField()),
                ('price_per_chair', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('salon_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_system.salontype')),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='bus_trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bus_trips', to='bus_system.bustrip'),
        ),
    ]
