# Generated by Django 3.2.19 on 2023-07-05 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_system', '0026_auto_20230705_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips_data',
            name='bus',
            field=models.ManyToManyField(blank=True, related_name='buses', to='bus_system.Bus'),
        ),
    ]
