# Generated by Django 3.2.19 on 2023-07-05 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus_system', '0027_alter_trips_data_bus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips_data',
            name='bus',
        ),
        migrations.AddField(
            model_name='trips_data',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buses', to='bus_system.bus'),
        ),
    ]
