# Generated by Django 3.2.19 on 2023-07-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_system', '0029_auto_20230706_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='payment_fee',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
