# Generated by Django 3.2.19 on 2023-07-08 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_system', '0030_alter_reservation_payment_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/'),
        ),
    ]
