# Generated by Django 3.2.19 on 2023-07-09 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_system', '0031_reservation_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='./media/barcodes/'),
        ),
    ]
