# Generated by Django 3.2.19 on 2023-07-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_system', '0032_alter_reservation_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
